### ISSUE TITLE
use custom nick when join conference from conference list

### ISSUE THREAD

**Issue by egproo** [atomarea/FlowX#16]
what about using custom nick when join an conference ?? if U want to add it i will try to add it .

**Comment by DoM1niC** [comment]
I think is feature is currently supported ???? If you look into in the Conference Details you setup your MUC Nick.

**Comment by egproo** [comment]
yes we can change nick from Conference Details after join .. i mean before join ..thanks

**Comment by egproo** [comment]
yes we can change nick from Conference Details after join .. i mean before join
 will showing dialog to type nickname after that will join to room .

**Comment by DoM1niC** [comment]
Ok no Problem :) but If you want to help us to fix some other issues .... I think your skiils are great or ??? :)

**Comment by DoM1niC** [comment]
Sounds ok but not necessary.... :( other Issues are more important now....
