### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [atomarea/FlowX#18]
As your app is not even available at Google Play: Do you plan to make it available here at Github? Sounds like an interesting project.

I'm currently using Conversations. Its F-Droid variant lacks the GCM support. So I'd be interested in taking a look at your fork. I guess the chat history could even be "migrated" between the two?

**Comment by DoM1niC** [comment]
Is possible but GCM is not include in our Build... We don't have enough skills to implemted this....

**Comment by IzzySoft** [comment]
I see. So your app is based on "Conversations w/o GCM"? I'd hoped for "with", but nevertheless: publishing the APK here could help making your app better known. Integrated Audio-Messages for example sounds like a nice thing to have. And if "data" can be migrated between FlowX and Conversations, I'd know some people who'd love to take a look at it :)

**Comment by DoM1niC** [comment]
The Dev from Conversation don't support such features like ours. A Playstore Version is currently online but we can't Update this Version because no access to this Google Account.

The APK could be download on https://flowx.im 
or https://github.com/atomarea/FlowX/releases

**Comment by IzzySoft** [comment]
Thanks, @DoM1niC – Play says the app is not available in my country. Guess I'm not the only one, so special thanks for attaching it here at Github. For automatic updates, the F-Droid client can be used with my repo, where you now can [find FlowX](https://apt.izzysoft.de/fdroid/index/apk/net.atomarea.flowx). Every time you publish a new `.apk` with a release (in `releases/`), it should be available via my repo within 24h – so feel free to point your users there :smile_cat:
